name: main.plugin.WorldTPPlugin
version: ${project.version}
main: main.plugin.WorldTPPlugin
api-version: 1.17
commands:
  t:
    description: Open a world tp gui for the player
  t add:
    description: Add a location
  t refresh:
    description: Refresh the locations from the DB
  t delete:
    description: Delete a location